# Generated by Django 4.0.4 on 2022-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.FloatField()),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('SKU', models.CharField(max_length=30, unique=True)),
                ('hay_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
